package net.danelegend.fatalhoes.captcha;

import org.bukkit.Material;

import java.util.Random;

public enum CaptchaItemData {
    ACTIVATOR_RAIL("ACTIVATOR_RAIL", Material.ACTIVATOR_RAIL),
    ANVIL("Anvil", Material.ANVIL),
    APPLE("Apple", Material.APPLE),
    BAKED_POTATO("Baked Potato", Material.BAKED_POTATO),
    BEACON("Beacon", Material.BEACON),
    BEDROCK("Bedrock", Material.BEDROCK),
    BLAZE_POWDER("Blaze Powder", Material.BLAZE_POWDER),
    BLAZE_ROD("Blaze Rod", Material.BLAZE_ROD),
    BONE("Bone", Material.BONE),
    BOOK("Book", Material.BOOK),
    BOOK_AND_QUILL("Book and Quill", Material.BOOK_AND_QUILL),
    BOW("Bow", Material.BOW),
    BOWL("Bowl", Material.BOWL),
    BREAD("Bread", Material.BREAD),
    BRICK("Brick Block", Material.BRICK),
    BRICK_STAIRS("Brick Stairs", Material.BRICK_STAIRS),
    BROWN_MUSHROOM("Brown Mushroom", Material.BROWN_MUSHROOM),
    BUCKET("Bucket", Material.BUCKET),
    CACTUS("Cactus", Material.CACTUS),
    CAKE("Cake", Material.CAKE),
    CARROT_ON_A_STICK("Carrot on a Stick", Material.CARROT_STICK),
    CAULDRON("Cauldron", Material.CAULDRON),
    CHAINMAIL_BOOTS("Chainmail Boots", Material.CHAINMAIL_BOOTS),
    CHAINMAIL_CHESTPLATE("Chainmail Chestplate", Material.CHAINMAIL_CHESTPLATE),
    CHAINMAIL_HELMET("Chainmain Helmet", Material.CHAINMAIL_HELMET),
    CHAINMAIL_LEGGINGS("Chainmail Leggings", Material.CHAINMAIL_LEGGINGS),
    CHEST("Chest", Material.CHEST),
    CLAY("Clay Block", Material.CLAY),
    CLAY_BALL("Clay Ball", Material.CLAY_BALL),
    COAL("Coal", Material.COAL),
    COAL_ORE("Coal Ore", Material.COAL_ORE),
    COBBLESTONE_WALL("Cobblestone Wall", Material.COBBLE_WALL),
    COBBLESTONE("Cobblestone", Material.COBBLESTONE),
    COBBLESTONE_STAIRS("Cobblestone Stairs", Material.COBBLESTONE_STAIRS),
    COMPASS("Compass", Material.COMPASS),
    COOKED_BEEF("Cooked Beef", Material.COOKED_BEEF),
    COOKED_CHICKEN("Cooked Chicken", Material.COOKED_CHICKEN),
    COOKIE("Cookie", Material.COOKIE),
    DAYLIGHT_DETECTOR("Daylight Detector", Material.DAYLIGHT_DETECTOR),
    DEAD_BUSH("Dead Bush", Material.DEAD_BUSH),
    DETECTOR_RAIL("Detector Rail", Material.DETECTOR_RAIL),
    DIAMOND("Diamond", Material.DIAMOND),
    DIAMOND_AXE("Diamond Axe", Material.DIAMOND_AXE),
    DIAMOND_BLOCK("Diamond Block", Material.DIAMOND_BLOCK),
    DIAMOND_BOOTS("Diamond Boots", Material.DIAMOND_BOOTS),
    DIAMOND_CHESTPLATE("Diamond Chestplate", Material.DIAMOND_CHESTPLATE),
    DIAMOND_HELMET("Diamond Helmet", Material.DIAMOND_HELMET),
    DIAMOND_HOE("Diamond Hoe", Material.DIAMOND_HOE),
    DIAMOND_LEGGINGS("Diamond Leggings", Material.DIAMOND_LEGGINGS),
    DIAMOND_ORE("Diamond Ore", Material.DIAMOND_ORE),
    DIAMOND_PICKAXE("Diamond Pickaxe", Material.DIAMOND_PICKAXE),
    DIAMOND_SHOVEL("Diamond Shovel", Material.DIAMOND_SPADE),
    DIAMOND_SWORD("Diamond Sword", Material.DIAMOND_SWORD),
    REPEATER("Repeater", Material.DIODE),
    DIRT("Dirt", Material.DIRT),
    DISPENSER("Dispenser", Material.DISPENSER),
    DRAGON_EGG("Dragon Egg", Material.DRAGON_EGG),
    DROPPER("Dropper", Material.DROPPER),
    EGG("Egg", Material.EGG),
    EMERALD("Emerald", Material.EMERALD),
    EMERALD_BLOCK("Emerald Block", Material.EMERALD_BLOCK),
    EMERALD_ORE("Emerald Ore", Material.EMERALD_ORE),
    MAP("Empty Map", Material.MAP),
    ENCHANTED_BOOK("Enchanted Book", Material.ENCHANTED_BOOK),
    ENCHANTING_TABLE("Enchanting Table", Material.ENCHANTMENT_TABLE),
    ENDER_CHEST("Ender Chest", Material.ENDER_CHEST),
    ENDER_PEARL("Ender Pearl", Material.ENDER_PEARL),
    END_PORTAL_FRAME("End Frame", Material.ENDER_PORTAL_FRAME),
    END_STORE("End Stone", Material.ENDER_STONE),
    EXPERIENCE_BOTTLE("Bottle of Enchanting", Material.EXP_BOTTLE),
    TNT_MINECRAFT("Minecart with TNT", Material.EXPLOSIVE_MINECART),
    ENDER_EYE("Eye of Ender", Material.EYE_OF_ENDER),
    FEATHER("Feather", Material.FEATHER),
    FERMENTED_SPIDER_EYE("Fermented Spider Eye", Material.FERMENTED_SPIDER_EYE),
    FIRE_CHARGE("Fire Charge", Material.FIREWORK_CHARGE),
    FIRE("Fire", Material.FIRE),
    FIREWORK_ROCKET("Firework Rocket", Material.FIREWORK),
    FIREWORK_STAR("Nether Star", Material.NETHER_STAR),
    FISHING_ROD("Fishing Rob", Material.FISHING_ROD),
    FLINT("Flint", Material.FLINT),
    FLINT_AND_STEEL("Flint and Steel", Material.FLINT_AND_STEEL),
    FURNACE("Furnace", Material.FURNACE),
    GHAST_TEAR("Ghast Tear", Material.GHAST_TEAR),
    GLASS("Glass", Material.GLASS),
    GLASS_BOTTLE("Glass Bottle", Material.GLASS_BOTTLE),
    GLOWSTONE("Glowstone Block", Material.GLOWSTONE),
    GLOWSTONE_DUST("Glowstone Dust", Material.GLOWSTONE_DUST),
    GOLDEN_AXE("Golden Axe", Material.GOLD_AXE),
    GOLD_BLOCK("Gold Block", Material.GOLD_BLOCK),
    GOLDEN_BOOTS("Golden Boots", Material.GOLD_BOOTS),
    GOLDEN_CHESTPLATE("Golden Chestplate", Material.GOLD_CHESTPLATE),
    GOLDEN_HELMET("Golden Helmet", Material.GOLD_HELMET),
    GOLDEN_HOE("Golden Hoe", Material.GOLD_HOE),
    GOLD_INGOT("Gold Ingot", Material.GOLD_INGOT),
    GOLDEN_LEGGINGS("Golden Leggings", Material.GOLD_LEGGINGS),
    GOLD_NUGGET("Gold Nugget", Material.GOLD_NUGGET),
    GOLD_ORE("Gold Ore", Material.GOLD_ORE),
    GOLDEN_PICKAXE("Golden Pickaxe", Material.GOLD_PICKAXE),
    GOLDEN_SHOVEL("Golden Shovel", Material.GOLD_SPADE),
    GOLDEN_SWORD("Golden Sword", Material.GOLD_SWORD),
    GOLDEN_APPLE("Golden Apple", Material.GOLDEN_APPLE),
    GOLDEN_CARROT("Golden Carrot", Material.GOLDEN_CARROT),
    GRASS("Grass", Material.GRASS),
    GRAVEL("Gravel", Material.GRAVEL),
    COOKED_PORKCHOP("Cooked Porkchop", Material.GRILLED_PORK),
    HOPPER("Hopper", Material.HOPPER),
    HOPPER_MINECRAFT("Minecraft with Hopper", Material.HOPPER_MINECART),
    ICE("Ice", Material.ICE),
    IRON_AXE("Iron Axe", Material.IRON_AXE),
    IRON_BLOCK("Iron Block", Material.IRON_BLOCK),
    IRON_BOOTS("Iron Boots", Material.IRON_BOOTS),
    IRON_CHESTPLATE("Iron Chestplate", Material.IRON_CHESTPLATE),
    IRON_DOOR("Iron Door", Material.IRON_DOOR),
    IRON_HELMET("Iron Helmet", Material.IRON_HELMET),
    IRON_HOE("Iron Hoe", Material.IRON_HOE),
    IRON_INGOT("Iron Ingot", Material.IRON_INGOT),
    IRON_LEGGINGS("Iron Leggings", Material.IRON_LEGGINGS),
    IRON_ORE("Iron Ore", Material.IRON_ORE),
    IRON_PICKAXE("Iron Pickaxe", Material.IRON_PICKAXE),
    IRON_SHOVEL("Iron Shovel", Material.IRON_SPADE),
    IRON_SWORD("Iron Sword", Material.IRON_SWORD),
    ITEM_FRAME("Item Frame", Material.ITEM_FRAME),
    JACK_O_LANTERN("Jack o' Lantern", Material.JACK_O_LANTERN),
    JUKEBOX("Jukebox", Material.JUKEBOX),
    LADDER("Ladder", Material.LADDER),
    LAPIS_BLOCK("Lapis Lazuli Block", Material.LAPIS_BLOCK),
    LAPIS_ORE("Lapis Lazuli Ore", Material.LAPIS_ORE),
    LAVA_BUCKET("Bucket of Lava", Material.LAVA_BUCKET),
    LEAD("Lead", Material.LEASH),
    LEATHER("Leather", Material.LEATHER),
    LEATHER_BOOTS("Leather Boots", Material.LEATHER_BOOTS),
    LEATHER_CHESTPLATE("Leather Chestplate", Material.LEATHER_CHESTPLATE),
    LEATHER_HELMET("Leather Helmet", Material.LEATHER_HELMET),
    LEATHER_LEGGINGS("Leather Leggings", Material.LEATHER_LEGGINGS),
    LEVER("Lever", Material.LEVER),
    MAGMA_CREAM("Magma Cream", Material.MAGMA_CREAM),
    MELON_SLICE("Melon Slice", Material.MELON),
    MELON("Melon Block", Material.MELON_BLOCK),
    MELON_SEEDS("Melon Seeds", Material.MELON_SEEDS),
    MILK_BUCKET("Bucket of Milk", Material.MILK_BUCKET),
    MINECART("Minecart", Material.MINECART),
    MOSSY_COBBLESTONE("Mossy Cobblestone", Material.MOSSY_COBBLESTONE),
    MUSHROOM_STEW("Mushroom Soup", Material.MUSHROOM_SOUP),
    NAME_TAG("Name Tag", Material.NAME_TAG),
    NETHER_BRICK("Nether Brick Block", Material.NETHER_BRICK),
    NETHER_BRICK_STAIRS("Nether Brick Stairs", Material.NETHER_BRICK_STAIRS),
    NETHERRACK("Netherrack", Material.NETHERRACK),
    NOTE_BLOCK("Note Block", Material.NOTE_BLOCK),
    OBSIDIAN("Obsidian", Material.OBSIDIAN),
    PAINTING("Painting", Material.PAINTING),
    PAPER("Paper", Material.PAPER),
    POISONOUS_POTATO("Poisonous Potato", Material.POISONOUS_POTATO),
    POWERED_RAIL("Powered Rail", Material.POWERED_RAIL),
    PUMPKIN("Pumpkin", Material.PUMPKIN),
    PUMPKIN_PIE("Pumpkin Pie", Material.PUMPKIN_PIE),
    PUMPKIN_SEEDS("Pumpkin Seeds", Material.PUMPKIN_SEEDS),
    QUARTZ_BLOCK("Quartz Block", Material.QUARTZ_BLOCK),
    NETHER_QUARTZ_ORE("Quartz Ore", Material.QUARTZ_ORE),
    QUARTZ_STAIRS("Quartz Stairs", Material.QUARTZ_STAIRS),
    RAIL("Rails", Material.RAILS),
    BEEF("Uncooked Beef", Material.RAW_BEEF),
    CHICKEN("Uncooked Chicken", Material.RAW_CHICKEN),
    RED_MUSHROOM("Red Mushroom", Material.RED_MUSHROOM),
    REDSTONE("Redstone Dust", Material.REDSTONE),
    REDSTONE_BLOCK("Redstone Block", Material.REDSTONE_BLOCK),
    COMPARATOR("Redstone Comparator", Material.REDSTONE_COMPARATOR),
    REDSTONE_ORE("Redstone Ore", Material.REDSTONE_ORE),
    ROTTEN_FLESH("Rotten Flesh", Material.ROTTEN_FLESH),
    SADDLE("Saddle", Material.SADDLE),
    SAND("Sand", Material.SAND),
    SHEARS("Shears", Material.SHEARS),
    SLIME_BALL("Slime Ball", Material.SLIME_BALL),
    SNOWBALL("Snow Ball", Material.SNOW_BALL),
    SNOW_BLOCK("Snow Block", Material.SNOW_BLOCK),
    SOUL_SAND("Soul Sand", Material.SOUL_SAND),
    SPIDER_EYE("Spider Eye", Material.SPIDER_EYE),
    SPONGE("Sponge", Material.SPONGE),
    STICK("Stick", Material.STICK),
    STONE("Stone", Material.STONE),
    STONE_AXE("Stone Axe", Material.STONE_AXE),
    STONE_BUTTON("Stone Button", Material.STONE_BUTTON),
    STONE_HOE("Stone Hoe", Material.STONE_HOE),
    STONE_PICKAXE("Stone Pickaxe", Material.STONE_PICKAXE),
    STONE_SHOVEL("Stone Shovel", Material.STONE_SPADE),
    STONE_SWORD("Stone Sword", Material.STONE_SWORD),
    STRING("String", Material.STRING),
    SUGAR_CANE("Sugar Cane", Material.SUGAR_CANE),
    SUGAR("Sugar", Material.SUGAR),
    TNT("TNT", Material.TNT),
    TORCH("Torch", Material.TORCH),
    TRIPWIRE_HOOK("Tripwire Hook", Material.TRIPWIRE_HOOK),
    VINE("Vine", Material.VINE),
    CLOCK("Clock", Material.WATCH),
    WATER_BUCKET("Bucket of Water", Material.WATER_BUCKET),
    LILY_PAD("Lily Pad", Material.WATER_LILY),
    COBWEB("Cobweb", Material.WEB),
    WHEAT("Wheat", Material.WHEAT),
    WOODEN_AXE("Wooden Axe", Material.WOOD_AXE),
    WOODEN_HOE("Wooden Hoe", Material.WOOD_HOE),
    WOODEN_PICKAXE("Wooden Pickaxe", Material.WOOD_PICKAXE),
    WOODEN_SHOVEL("Wooden Shovel", Material.WOOD_SPADE),
    WOODEN_SWORD("Wooden Sword", Material.WOOD_SWORD),
    CRAFTING_TABLE("Crafting Table", Material.WORKBENCH),
    WRITTEN_BOOK("Written Book", Material.WRITTEN_BOOK);

    private String displayName;
    private Material material;

    CaptchaItemData(final String displayName, final Material material) {
        this.displayName = displayName;
        this.material = material;
    }

    public String getDisplayName() {
        return this.displayName;
    }

    public Material getMaterial() {
        return this.material;
    }

    public static CaptchaItemData getRandomItem() {
        Random random = new Random();
        return values()[random.nextInt(values().length)];
    }

}
