# Options for harvester hoes
harvester-hoe:
  cane-price: 50
  name: '&c&lHarvester Hoe'
  lore:
  - ''
  - '&fUse this magical hoe to automatically collect'
  - '&fSugarcane. Use &c/upgrade &fwhile holding to enchant'
  glow: true
  spawner-drops:
   enabled: true
  key-drops:
   enabled: true
   # Use {player} as a placeholder for the player name
   # Type in the command to give the player a crate here 
   key-command: 'give {player} crate'
  cane-top-gui:
   title: '&cCane Top Placements'
  # Configurability for Enchants  
  Autosell:
   Base-Token-Cost: 50000 # Price for level 1
   Max-Level: 1 # Max level for this enchant
   Price-Multiplier: 0.01
   # How much each increasing level should cost
   # Cost Example
   # Level 1 = basePrice * 1.00
   # Level 2 = basePrice * 1.01
   # Level 3 = basePrice * 1.02
   # ...
  AutosellBooster:
   Base-Token-Cost: 10000
   Max-Level: 100
   Price-Multiplier: 0.01
  Shockwave:
   Base-Token-Cost: 50000
   Max-Level: 1
   Price-Multiplier: 0
  DropBooster:
   Base-Token-Cost: 10000
   Max-Level: 100
   Price-Multiplier: 0.01
  TokenBooster:
   Base-Token-Cost: 10000
   Max-Level: 100
   Price-Multiplier: 0.01
  SpawnerLooting:
   Base-Token-Cost: 10000
   Max-Level: 100
   Price-Multiplier: 0.01
   # Probability of looting spawner
   # Chance Calculated by enchantLevel/Probability
   Probability: 10000
  KeyLooting:
   Base-Token-Cost: 10000
   Max-Level: 100
   Price-Multiplier: 0.01
   Probability: 10000
  Haste:
   Base-Token-Cost: 10000
   Max-Level: 100
   Price-Multiplier: 0.01
   

# Configurable display for the help menu. Particularly useful if you have a certain color scheme
help:
  admin:
  - '&8<------ &c&lFatality Hoes &8----->'
  - '&7● /upgrade - Opens up the upgrade and stats menu for you and your harvester hoe'
  - '&7● /cane top - Displays the top 7 players who have mined the most cane'
  - '&7● /tokens - Displays how many tokens you have'
  - '&7● /cane - Displays how much cane you have mined'
  - '&7● /harvester give {player} {amount} [max] - Gives the amount of harvester hoes to the player. If the max flag is chosen, the hoe will be maxed out on enchants'
  - '&7● /tokens give {player} {amount} - Gives the player the amount of tokens'
  - '&7● /tokens subtract {player} {amount} - Removes the amount from the players tokens'
  - '&7● /tokens set {player} {amount} - Sets the players tokens to amount'
  player:
  - '&8<------ &c&lFatality Hoes &8----->'
  - '&7● /upgrade - Opens up the upgrade and stats menu for you and your harvester hoe'
  - '&7● /cane top - Displays the top 7 players who have mined the most cane'
  - '&7● /tokens - Displays how many tokens you have'
